# Generated by Django 5.1.6 on 2025-02-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_by',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=1, upload_to='post_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
