# Generated by Django 5.1.6 on 2025-02-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_post_by_post_post_image_post_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
    ]
